project/courses/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'courses'
urlpatterns = [
    path(route='', view=views.CourseListView.as_view(), name='index'),
    path('registration/', views.registration_request, name='registration'),
    path('login/', views.login_request, name='login'),
    path('logout/', views.logout_request, name='logout'),
    path('<int:pk>/', views.CourseDetailView.as_view(), name='course_details'),
    path('<int:course_id>/enroll/', views.enroll, name='enroll'),
    
    path('<int:course_id>/submit/', views.submit, name='submit'),
    path('<int:course_id>/show_exam_result/', views.show_exam_result, name='show_exam_result'),

 ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('courses/', include('courses.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/courses/models.py
import sys
from django.utils.timezone import now
from django.template.defaultfilters import default
try:
    from django.db import models
except Exception:
    print("There was an error loading django modules. Do you have django installed?")
    sys.exit()

from django.conf import settings
import uuid


# Instructor model
class Instructor(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    id=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    full_time = models.BooleanField(default=True)
    total_learners = models.IntegerField()

    def __str__(self):
        return self.user.username


# Learner model
class Learner(models.Model):
    id=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    STUDENT = 'student'
    DEVELOPER = 'developer'
    DATA_SCIENTIST = 'data_scientist'
    DATABASE_ADMIN = 'dba'
    OCCUPATION_CHOICES = [
        (STUDENT, 'Student'),
        (DEVELOPER, 'Developer'),
        (DATA_SCIENTIST, 'Data Scientist'),
        (DATABASE_ADMIN, 'Database Admin')
    ]
    occupation = models.CharField(
        null=False,
        max_length=20,
        choices=OCCUPATION_CHOICES,
        default=STUDENT
    )
    social_link = models.URLField(max_length=200)

    def __str__(self):
        return self.user.username + "," + \
               self.occupation


# Course model
class Course(models.Model):
    id=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    name = models.CharField(null=False, max_length=30, default='online course')
    image = models.ImageField(upload_to='course_images/')
    description = models.CharField(max_length=1000)
    pub_date = models.DateField(null=True)
    instructors = models.ManyToManyField(Instructor)
    users = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Enrollment')
    total_enrollment = models.IntegerField(default=0)
    is_enrolled = False

    def __str__(self):
        return "Name: " + self.name + "," + \
               "Description: " + self.description


# Lesson model
class Lesson(models.Model):
    id=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    title = models.CharField(max_length=200, default="title")
    order = models.IntegerField(default=0)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    content = models.TextField()


# Enrollment model
class Enrollment(models.Model):
    AUDIT = 'audit'
    HONOR = 'honor'
    BETA = 'BETA'
    COURSE_MODES = [
        (AUDIT, 'Audit'),
        (HONOR, 'Honor'),
        (BETA, 'BETA')
    ]
    id=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    date_enrolled = models.DateField(default=now)
    mode = models.CharField(max_length=5, choices=COURSE_MODES, default=AUDIT)
    rating = models.FloatField(default=5.0)

class Question(models.Model):
    '''Used to persist question content for a course'''
    id=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    text = models.CharField(max_length=200)
    grade=models.FloatField(default=1.0)
    course= models.ForeignKey(Course, on_delete=models.CASCADE)
    def choices_correct_ids(self):
        selected_list=[]
        for correct in self.choice_set.filter(is_correct=True):
            selected_list.append(correct.id)
        return selected_list
    
    def choices_not_correct_ids(self):
        selected_list=[]
        for correct in self.choice_set.filter(is_correct=False):
            selected_list.append(correct.id)
        return selected_list
    
    def choices_ids(self):
        selected_list=[]
        for correct in self.choice_set.all():
            selected_list.append(correct.id)
        return selected_list
        
    def classification(self, selected_ids):
        classification = {"selected_but_false":[],
                          "selected_and_true":[],
                          "not_selected_and_false":[],
                          "not_selected_but_true":[]}     
        selected_ids =   [id for id in selected_ids if id in   self.choices_ids()]
        not_selected_id = [id for id in self.choices_ids() if id not in set(selected_ids)]
        
        classification["selected_but_false"] = [id for id in selected_ids if id  in set(self.choices_not_correct_ids())]
        classification["selected_and_true"] = [id for id in selected_ids if id  in set(self.choices_correct_ids())]
        classification["not_selected_and_false"] = [id for id in not_selected_id if id  in set(self.choices_not_correct_ids())]
        classification["not_selected_but_true"] = [id for id in not_selected_id if id  in set(self.choices_correct_ids())]
        return classification
    
    def is_get_score(self, selected_ids):
        all_answers = self.choice_set.filter(is_correct=True).count()
        selected_correct = self.choice_set.filter(is_correct=True, id__in=selected_ids).count()
        selected_not_correct =self.choice_set.filter(is_correct=False, id__in=selected_ids).count()
        if all_answers == selected_correct and selected_not_correct == 0:
            return True
        else:
            return False      
    
class Choice(models.Model):
    ''' Used to persist choice content for a question '''
    id=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    text = models.CharField(max_length=200) 
    is_correct = models.BooleanField(default=False) 
    question= models.ForeignKey(Question, on_delete=models.CASCADE) 
    
class Submission(models.Model): 
    ''' Used to link an enrollment to multiples choices''' 
    id=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    enrollment=models.ForeignKey(Enrollment, on_delete=models.CASCADE) 
    choices = models.ManyToManyField(Choice)
    

project/courses/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Course, Enrollment, Question, Choice, Submission
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from django.contrib.auth import login, logout, authenticate
import math
import logging
# Get an instance of a logger
logger = logging.getLogger(__name__)
# Create your views here.


def registration_request(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'courses/user_registration_bootstrap.html', context)
    elif request.method == 'POST':
        # Check if user exists
        username = request.POST['username']
        password = request.POST['psw']
        first_name = request.POST['firstname']
        last_name = request.POST['lastname']
        user_exist = False
        try:
            User.objects.get(username=username)
            user_exist = True
        except:
            logger.error("New user")
        if not user_exist:
            user = User.objects.create_user(username=username, first_name=first_name, last_name=last_name,
                                            password=password)
            login(request, user)
            return redirect("courses:index")
        else:
            context['message'] = "User already exists."
            return render(request, 'courses/user_registration_bootstrap.html', context)


def login_request(request):
    context = {}
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['psw']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('courses:index')
        else:
            context['message'] = "Invalid username or password."
            return render(request, 'courses/user_login_bootstrap.html', context)
    else:
        return render(request, 'courses/user_login_bootstrap.html', context)


def logout_request(request):
    logout(request)
    return redirect('courses:index')


def check_if_enrolled(user, course):
    is_enrolled = False
    if user.id is not None:
        # Check if user enrolled
        num_results = Enrollment.objects.filter(user=user, course=course).count()
        if num_results > 0:
            is_enrolled = True
    return is_enrolled


# CourseListView
class CourseListView(generic.ListView):
    template_name = 'courses/course_list_bootstrap.html'
    context_object_name = 'course_list'

    def get_queryset(self):
        user = self.request.user
        courses = Course.objects.order_by('-total_enrollment')[:10]
        for course in courses:
            if user.is_authenticated:
                course.is_enrolled = check_if_enrolled(user, course)
        return courses


class CourseDetailView(generic.DetailView):
    model = Course
    template_name = 'courses/course_detail_bootstrap.html'


def enroll(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    user = request.user

    is_enrolled = check_if_enrolled(user, course)
    if not is_enrolled and user.is_authenticated:
        # Create an enrollment
        Enrollment.objects.create(user=user, course=course, mode='honor')
        course.total_enrollment += 1
        course.save()

    return HttpResponseRedirect(reverse(viewname='courses:course_details', args=(course.id,)))

def extract_answers_request(request):
    submitted_anwsers = []
    for key in request.POST:
        if key.startswith('choice'):
            value = request.POST[key]
            choice_id = int(value)
            submitted_anwsers.append(choice_id)
    return submitted_anwsers

def extract_answers_submisison(submission):
    submitted_anwsers = []
    for choice in submission.choices.all():
            choice_id = choice.id
            submitted_anwsers.append(choice_id)
    return submitted_anwsers




def submit(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    user = request.user
    
    if user.is_authenticated:
        enrollment = Enrollment.objects.get(user=user, course=course)
        my_submission = Submission.objects.create(enrollment=enrollment)
        submitted_anwsers=extract_answers_request(request)
        for submitted_anwser in submitted_anwsers:
            my_submission.choices.add(Choice.objects.get(id=submitted_anwser))
    context = {"course_id":course_id,"submission.id":my_submission.id}
    return show_exam_result(request, course_id, my_submission.id)


def show_exam_result(request, course_id, submission_id):
    submission = get_object_or_404(Submission, pk=submission_id)
    course = get_object_or_404(Course, pk=course_id)
    selected_choices_id_list=extract_answers_submisison(submission)
    questions=Question.objects.filter(course=course.id)
    context = {}
    context["submission"]=submission
    context["course"]=course
    context["total_score"]=0.0
    context['score']=0.0
    context["questions"]=[]
    for question in questions:
        question_dict={}
        classification=question.classification(selected_choices_id_list)
        question_dict["text"]=question.text
        context["total_score"]=context["total_score"]+question.grade
        context['score']=context['score']+question.grade/len(question.choices_correct_ids())*max(0,
            len(classification["selected_and_true"])-
            2*len(classification["selected_but_false"]))
        question_dict["choices"]=[]
        for choice_id in classification["selected_and_true"]:
            question_dict["choices"].append({"status":"selected_and_true","text":Choice.objects.get(id=choice_id).text})
        for choice_id in classification["selected_but_false"]:
            question_dict["choices"].append({"status":"selected_but_false","text":Choice.objects.get(id=choice_id).text}) 
        for choice_id in classification["not_selected_but_true"]:
            question_dict["choices"].append({"status":"not_selected_but_true","text":Choice.objects.get(id=choice_id).text})
        for choice_id in classification["not_selected_and_false"]:
            question_dict["choices"].append({"status":"not_selected_and_false","text":Choice.objects.get(id=choice_id).text})
        if len(classification["not_selected_but_true"])>0:
            question_dict["choices"].append({"status":"missing"})
        context["questions"].append(question_dict)
    context["total_per_cent"]=context['score']/context["total_score"]
    print(str(context['score'])+"/"+str(context["total_score"]))
    print(context)
    return render(request, 'courses/exam_result_bootstrap.html', context)

project/courses/templates/courses/course_detail_boostrap.html
<!DOCTYPE html>
<html lang="en">
<head>
     {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
</head>

<body>
    <!-- Navigation bar -->
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                  <a class="navbar-brand" href="{% url 'courses:index' %}">Home</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
                    <a class="btn btn-link" href="{% url 'courses:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'courses:login' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username" >
                            <input type="password" class="form-control" placeholder="Username" name="psw" >
                            <button class="btn btn-primary" type="submit">Login</button>
                            <a class="btn btn-link" href="{% url 'courses:registration' %}">Sign Up</a>
                        </div>
                    </form>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- Page content -->
    <div class="container-fluid"> <h2>{{ course.name }}</h2>
     <a href="#courses" data-toggle="collapse"><b>LESSONS</b> click to collapse</a> 
     <div id="courses" class="collapse">
   	 <div class="cont<h2>{{ course.name }}</h2>
            <div class="card-columns-vertical">
                {% for lesson in course.lesson_set.all %}
                    <div class="card mt-1">
                        <div class="card-header"><a href="#course{{forloop.counter}}" data-toggle="collapse"><h5>Lesson of {{lesson.title}}</h5></a></div>
                        <div class="card-body collapse" id="course{{forloop.counter}}" style="padding:2px; padding-left:25px;">{{lesson.content}}</div>
                    </div>
                {% endfor %}
            </div>
     </div>
   	 </div></div>
     <div class="container-fluid">     
           <a href="#exam" data-toggle="collapse"><b>EXAMS</b> click to collapse</a> 
            <div div id="exam" class="collapse">
           	{% if user.is_authenticated %}
           	<form id="questionform" action="{% url 'courses:submit' course.id %}" method="post">
            	<div>
            		{% for question in course.question_set.all %}
            		<div class="card mt-1">
            			<div class="card-header"><h5>{{ question.text}}</h5></div>
            			 <!--<h5>Question : {{ question.text }}</h5>-->
            				<div class="card mt-1"><div class="card mt-1">{% csrf_token %}
            				<div class="form-group">
            				{% for choice in question.choice_set.all %}
            				<div class="form-check">
                                    <label class="form-check-label">
                                        <input type="checkbox" name="choice_{{choice.id}}"
                                               class="form-check-input" id="{{choice.id}}"
                                               value="{{choice.id}}">{{ choice.text }}
                                    </label>
                           	</div>
            				{% endfor %}
            				</div>
            				</div>
            			</div>
            		{% endfor %}
            	</div>
            	<input class="btn btn-success btn-block" type="submit" value="Submit">
            </form>
            {% else %}
            	<p>
            	Please authenticate yourself for exam displaying !
            	</p>
            {% endif %}
            </div>
           
    </div>
</body>
</html>

project/courses/templates/courses/course_list_bootstrap.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <meta charset="UTF-8">
    <title>Online Courses</title>
</head>
<body>
    <!-- Navigation bar -->
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                  <a class="navbar-brand" href="#">Online Course</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
                    <a class="btn btn-link" href="{% url 'courses:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'courses:login' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username" >
                            <input type="password" class="form-control" placeholder="Username" name="psw" >
                            <button class="btn btn-primary" type="submit">Login</button>
                            <a class="btn btn-link" href="{% url 'courses:registration' %}">Sign Up</a>
                        </div>
                    </form>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- Page content -->
    {% if course_list %}
        <div class="container">
            <div class="card-deck">
                {% for course in course_list %}
                         <div class="card" style="width: 36rem;">
                          <img class="card-img-left" src="{{MEDIA_URL}}/{{ course.image }}" width="240px" height="240px"
                               alt="Course image">
                          <div class="card-body bg-light">
                              <h5 class="card-title">{{ course.name }}, <span class="text-success">
                                  {{ course.total_enrollment}} enrolled</span></h5>
                            <p class="card-text">{{ course.description}}</p>
                            <form action="{% url 'courses:enroll' course.id %}" method="post">
                                  {% csrf_token %}
                                  <input class="btn btn-primary"  type="submit"
                                         value="{% if course.is_enrolled %}Enter{% else %}Enroll{% endif %} ">
                            </form>
                          </div>
                        </div>
                {% endfor %}
            </div>
        </div>
    {% else %}
        <p>No courses are available.</p>
    {% endif %}
</body>
</html>

project/courses/templates/courses/exam_result_bootstrap.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>

 <nav class="navbar navbar-light bg-light">
    <div class="container-fluid">
        <div class="navbar-header">
              <a class="navbar-brand" href="{% url 'courses:index' %}">Home</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li>
                <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
                <a class="btn btn-link" href="{% url 'courses:logout' %}">Logout</a>
            </li>
            {% else %}
            <li>
                <form class="form-inline" action="{% url 'courses:login' %}" method="post">
                    {% csrf_token %}
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Username" name="username" >
                        <input type="password" class="form-control" placeholder="Username" name="psw" >
                        <button class="btn btn-primary" type="submit">Login</button>
                        <a class="btn btn-link" href="{% url 'courses:registration' %}">Sign Up</a>
                    </div>
                </form>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="container-fluid">
<div class="page-header">
	{% load humanize %}
    {% if 0.8 > total_per_cent %}
    	<div>
        <div class="alert alert-danger">
        	<b>Failed</b> Sorry, {{user.first_name}}, you have failed exam with score {{score|floatformat:2|intcomma}}/{{total_score|floatformat:2|intcomma}}
            <!--HINT Display failed info -->
        </div>
       <!--   {% comment class="btn btn-link text-danger" %}       -->
       <h1><a href="{% url 'courses:course_details' course.id %}"><b>Re-test</b></a> </h1>
       <!--   {% endcomment %}   -->
       </div>
    {% else %}     
       <div class="alert alert-success">
       		<b>Congratulations, {{user.first_name}} </b> You have passed the exam and completed the course with score of {{score|floatformat:2|intcomma}}/{{total_score|floatformat:2|intcomma}}
    	</div>
    {% endif %}
    {% if total_per_cent < 0.8 %}
    <div>
    	<h5><a class="btn btn-link text-danger" href="{% url 'courses:course_details' course.id %}"><b>Re-test</b></a> </h5>
    </div>
    {% endif %}
    <p>
</div>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
 <div class="container-fluid">
  <h3 class="my-0 mr-md-auto font-weight-normal align-items-center">Exam Results </h3>
    {% for question in questions %}
    	<div class="jumbotron border rounded-5>" style="padding:2px; padding-left:5px;">
    	<h4>{{question.text}}</h4>
    	{% for choice in question.choices %}
	    	{% if choice.status == "selected_and_true" %}
	    		<div style="color:green; padding-left:15px;">Correct answer : 
 	    	{% elif choice.status == "selected_but_false" %}
	    		<div style="color:red; padding-left:15px;">Incorrect answer : 
			{% else %}
	    		<div style="padding-left:15px;">
	    	{% endif %}
	    		{{choice.text}}</div>
	    	{% if choice.status == "missing" %}
	    	<h6 style="color:blue;">Some good response(s), is(are) not selected !</h6>
	    	{% endif %}
    	{% endfor %}
    	</div>
    {% endfor %}
    </div>
    </p>
    </div>       <!--HINT Display exam results-->
</body>
</html>

project/courses/templates/courses/user_login_bootstrap.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>

<!-- Navigation bar -->
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'courses:index' %}">Home</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
                    <a class="btn btn-link" href="{% url 'courses:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'courses:login' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username" >
                            <input type="password" class="form-control" placeholder="Username" name="psw" >
                            <button class="btn btn-primary" type="submit">Login</button>
                            <a class="btn btn-link" href="{% url 'courses:registration' %}">Sign Up</a>
                        </div>
                    </form>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- Stylize Login form -->
    <form action="{% url 'courses:login' %}" method="post">
        {% csrf_token %}
        <div class="container"> <!--Style root div with .container class -->
            <h1>Login</h1>
            <div class="form-group"> <!--Style second div with .form-group class -->
              <label for="username"><b>User Name</b></label>
              <input id="username" class = "form-control" type="text" placeholder="Enter User Name: " name="username" required> <!--Style input with .form-control class -->
              <label for="psw"><b>Password</b></label>
              <input id="psw" class = "form-control" type="password"  placeholder="Enter Password: " name="psw" required> <!--Style input with .form-control class -->
            </div>
            {% if message %}
              <div class="alert alert-warning"> <!--Style the message paragraph with .alert and .alert-warning class -->
                {{ message }}
              </div>
            {% endif %}
            <button class="btn btn-primary" type="submit">Login</button> <!--Style button with .btn and .btn-primary class -->
        </div>
    </form>

</body>

project/courses/templates/courses/user_registration_bootstrap.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>

    <!-- Navigation bar -->
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'courses:index' %}">Home</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
                    <a class="btn btn-link" href="{% url 'courses:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'courses:login' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username" >
                            <input type="password" class="form-control" placeholder="Username" name="psw" >
                            <button class="btn btn-primary" type="submit">Login</button>
                            <a class="btn btn-link" href="{% url 'courses:registration' %}">Sign Up</a>
                        </div>
                    </form>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- Stylize Registration form -->
    <form action="{% url 'courses:registration' %}" method="post">
        <div class="container"> <!--Style root div with .container class -->
            {% csrf_token %}
            <h1>Sign Up</h1>
            <hr>
            <div class="form-group"> <!--Style second div with .form-group class -->
                <label for="username"><b>User Name</b></label>
                <input type="text" class="form-control" placeholder="Enter User Name: " name="username" required> <!--Style input with .form-control class -->
                <label for="firstname"><b>First Name</b></label>
                <input type="text" class="form-control" placeholder="Enter First Name: " name="firstname" required> <!--Style input with .form-control class -->
                <label for="lastname"><b>Last Name</b></label>
                <input type="text" class="form-control" placeholder="Enter Last Name: " name="lastname" required> <!--Style input with .form-control class -->
                <label for="psw"><b>Password</b></label>
                <input type="password" class="form-control" placeholder="Enter Password: " name="psw" required> <!--Style input with .form-control class -->
                {% if message %}
                <div class="alert alert-warning"> <!--Style the message paragraph with .alert and .alert-warning class -->
                    {{ message }}
                </div>
                {% endif %}
                <button class="btn btn-primary" type="submit">Sign up</button> <!--Style button with .btn and .btn-primary class -->
            </div>
        </div>
    </form>

</body>